### PR TITLE
Make the library threadsafe

### LINKED ISSUE #81: Threading problem of c library.
Definitely sep is a good idea, especially the c library makes it easier to build a customized "sextractor", but now I met some performance problem. Because of the widely use of multi core CPU, obviously the multi threading is a efficient way.
But after some test, multi threading failed, maybe the reason of some global variables. 
So, is that possible to make a library suitable for multi-threading, or is that possible to support openmp in sep?

### PR DESCRIPTION
**Pull request by RReverser**
As mentioned in #81, currently the library is not thread-safe, that is, it can't even be used on multiple separate images in parallel due to the shared global mutable variables.

There are a couple of ways to fix this. I've mostly done refactoring in a separate branch to pass everything around via params, but that kind of a change is rather huge and harder to review for correctness.

So I took a different approach I mentioned in https://github.com/kbarbary/sep/issues/81#issuecomment-782900672, and instead went through all the statics and changed them depending on usage:

1. Into local function variables where they are initialized every time anyway - those clearly don't have to be `static`.
2. Into `const static` if it was a static that's been always initialised to the same constant value - there was just `initinfo` that fell into this category.
3. Into `_Atomic` if it's a global config - in particular `sub_object_limit` and `extract_pixstack` params. I believe there is no point in configuring those per-thread, so just left them as globals, but `_Atomic` ensures safe complete initialization in case of a race.
4. Finally, made all the other mutable statics `_Thread_local`, which ensures that none of the threads will override each others' data while storing temporary information about the image being processed.

Then, I used `clang-tidy` to:

1. Find and auto-mark all places where pointers can be `const` - this allows consumer to more easily reason about which data can be shared across images and/or threads, and which will be mutated internally by SEP and so needs to have separate copies per run.
2. Detect all non-thread-safe functions (clang-tidy can do this starting from LLVM 13). Such function was only `rand`, so I added a `_Thread_local` seed variable `randseed`, and switched those callsites to `rand_r(&randseed)`, making those thread-safe too.

Note that due to trimming of unnecessary spacing by clang-tidy and editors the diffs can look a bit more bloated, so I suggest to review the diff using "ignore whitespace changes" mode here: https://github.com/kbarbary/sep/compare/master...RReverser:simple-threadsafe?expand=1&w=1

Overall I think this is the least invasive change that should be relatively easy to review for correctness (and, of course, I checked that all the tests are passing), while at the same time ensures thread-safety throughout the codebase.

Fixes #81.

### CODE REVIEW

File: ctest/test_image.c [hunk 1]
```diff
@@ -32,60 +32,14 @@ float *uniformf(float a, float b, int n)
...
-    
+
   result = (float*)malloc(n*sizeof(float));
   for (i=0; i<n; i++)
     result[i] = a + (b-a) * rand() / ((double)RAND_MAX);
 
   return result;
 }
 
-double gaussrand()
```
Comment (RReverser) [inline ctest/test_image.c:43]: Ah yes, I also removed this because while looking for `static`s in the codebase that need to be updated for thread-safety, I've noticed that those functions are unused altogether, so just removed them.

File: src/sepcore.h [hunk 2]
```diff
@@ -33,7 +33,7 @@
 #define UNKNOWN_NOISE_TYPE  10
 
 #define	BIG 1e+30  /* a huge number (< biggest value a float can store) */
-#define	PI  3.1415926535898
+#define	PI  M_PI
```
Comment (RReverser) [inline src/sepcore.h:36]: This is something that `clang-tidy` also noticed during its runs and thought it's worth the minor cleanup too.

**Comment by RReverser** [comment]
I can split out `const` pointer and such changes separately btw, it just was easier to fix them together, and it's semi-related to thread safety as well.

**Comment by RReverser** [comment]
Also I still think it's a good idea to make some refactorings to isolate data further, but I think it's worth implementing the minimal / least invasive change first, that already guarantees thread-safety at least for independent inputs and outputs isolated to their own threads, and then it's easier to do further improvements on top of it.

**Comment by RReverser** [comment]
@kbarbary Hey! I suspect you're busy, but just in case it got miseed - does this approach make sense in general?

**Comment by kbarbary** [comment]
Sorry for the delay, this is really impressive work! It looks good to me. It might be worth adding a note to the unreleased version in CHANGES.md explaining the implications. I think you'd be more qualified to write it than me. Want to add that and I'll merge it?

**Comment by RReverser** [comment]
@kbarbary Happy to do so, but I'll probably need clarification on versioning (#111) before I can add an entry to CHANGES.md.

**Comment by RReverser** [comment]
@kbarbary I've pushed commit with description of changes in CHANGES.md, but left version line as `vTODO` - please substitute with whatever is deemed appropriate depending on resolution of #111.

**Comment by RReverser** [comment]
Ah I see you used `unreleased` line upstream, will add there during rebase.

**Comment by RReverser** [comment]
There is a lot more in terms of pointers that could be constified, but they all need manual review, and I'll probably leave them for a separate PR.

**Comment by RReverser** [comment]
@kbarbary Thanks!

**Comment by kbarbary** [comment]
Thank you! Again, great work.

**Comment by kbarbary** [comment]
Should I do a version release?

**Comment by RReverser** [comment]
@kbarbary I think tagging 1.2.0 and updating `sep_version_string` is reasonable at this point, yeah. Any further improvements can always be released under patch version bumps.

**Comment by RReverser** [comment]
> @kbarbary I think tagging 1.2.0 and updating `sep_version_string` is reasonable at this point, yeah. Any further improvements can always be released under patch version bumps.

Assuming you haven't done that yet, I have a follow-up that could be also merged as part of 1.2.0 release tag :)
